<?php

namespace App\Services;

class GeminiAIService
{
    private $apiKey;

    public function __construct()
    {
        $this->apiKey = env('GEMINI_API_KEY');
    }

    public function generateCareerAdvice($mbti)
    {
        // NEW API ENDPOINT (v1beta2)
        $url = "https://generativelanguage.googleapis.com/v1beta2/models/gemini-1.5-flash:generateContent?key={$this->apiKey}";

        $prompt = "
        You are an expert career counselor.
        The user's MBTI personality type is: $mbti.

        Provide:
        - A short personality summary
        - Strengths
        - Weaknesses  
        - Five best-suited careers + explanation  
        - A motivational message  

        Keep the answer clean and friendly.
        ";

        // NEW API STRUCTURE
        $data = [
            "contents" => [
                [
                    "role" => "user",
                    "parts" => [
                        ["text" => $prompt]
                    ]
                ]
            ]
        ];

        $payload = json_encode($data);

        $ch = curl_init();

        curl_setopt_array($ch, [
            CURLOPT_URL => $url,
            CURLOPT_POST => true,
            CURLOPT_HTTPHEADER => ["Content-Type: application/json"],
            CURLOPT_POSTFIELDS => $payload,
            CURLOPT_RETURNTRANSFER => true
        ]);

        $response = curl_exec($ch);
        curl_close($ch);

        $result = json_decode($response, true);
        dd($result);


        // SAFE EXTRACTION
        if (isset($result["candidates"][0]["content"]["parts"][0]["text"])) {
            return $result["candidates"][0]["content"]["parts"][0]["text"];
        }

        if (isset($result["candidates"][0]["content"][0]["parts"][0]["text"])) {
            return $result["candidates"][0]["content"][0]["parts"][0]["text"];
        }

        if (isset($result["error"]["message"])) {
            return "API Error: " . $result["error"]["message"];
        }

        return "No response generated by AI.";
    }
}
